### ISSUE TITLE
[BUG] Match statement syntax not supported

### ISSUE THREAD

**Issue by sondrelg** [hadialqattan/pycln#115]
Hi,

Thanks for creating this project. It's been super helpful 👏 

Ran into an issue with match statement syntax on the last version (1.2.5), running the project as a pre-commit hook. Looks like match statement support was added a while ago, so not sure if I'm just tired or there's an actual bug in the hook 🙃

### Reproducible example

Python code
```python
# match.py
match 1:
    case 1:
        print('nice')
    case _:
        print('what')
```

Pre-commit config
```yaml
# pre-commit-config.yaml
repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5
    hooks:
      - id: pycln
 ```

Output
````
  match.py:1:7 SyntaxError: invalid syntax 'match 1:' ⛔
