### ISSUE TITLE
[FEATURE] pycln doesn't clean __init__.py files that lack __all__ dunder.

### ISSUE THREAD

**Issue by Goldziher** [hadialqattan/pycln#166]
Hi,

So I have an `__init__.py` file with a bunch of unused imports and another file in the same test folder that also has a bunch of missing imports. The regular test file is cleaned, but the `__init__.py` file is not cleaned.

I see the docs regarding the `__all__` dunder. I think this should be configurable. If my pyproject.toml has:

```toml
[tool.pycln]
all = true
```

It should clean all files. Alternatively this could be explicit:

```toml
[tool.pycln]
all = true
require_all_dunder_in_init = false
```
