### ISSUE TITLE
[BUG] Exception groups syntax from python 3.11 not supported 

### ISSUE THREAD

**Issue by lulingar** [hadialqattan/pycln#240]
I have a project that invokes pycln from pre-commit. The project targets python 3.11+. I'm using exception groups due to using Trio. However, when I run pre-commit I get a syntax error

**To Reproduce** Steps to reproduce the behavior:

1. Take this pre-commit configuration:

   ```yaml
   ---
   default_language_version:
     python: python3.11
   repos:
     - repo: https://github.com/pre-commit/pre-commit-hooks
       rev: v4.4.0
       hooks:
         - id: trailing-whitespace
         - id: check-docstring-first
         - id: check-json
         - id: pretty-format-json
           args: [--autofix, --no-sort-keys]
         - id: check-added-large-files
         - id: debug-statements
     - repo: https://github.com/hadialqattan/pycln
       rev: v2.4.0
       hooks:
         - id: pycln
           args: [--all]
     - ...        
   ```

and the following source file:

   ```python
   import logging
   
   import trio
   from hypercorn.config import Config
   from hypercorn.trio import serve
   logger = logging.getLogger(__name__)
   
   LISTEN_PORT: int = 8000
   
   
   def run_serve() -> None:
       trio.run(server_main)
   
   
   async def server_main() -> None:
       from local_console.fastapi.main import app as fastapi
   
       config = Config()
       config.bind = [f"localhost:{LISTEN_PORT}"]
       config.accesslog = logging.getLogger("hypercorn.access")
   
       try:
           await serve(fastapi, config)
       except* Exception as excgroups:
           for group in excgroups.exceptions:
               for exc in group.exceptions:
                   if isinstance(exc, OSError) and exc.errno == 98:
                       logger.error(
                           f"Cannot start API server since port {LISTEN_PORT} is used by another process."
                       )
                   else:
                       logger.error("Cannot start API server due to:", exc_info=exc)
   ```

2. Run Pycln via pre-commit command, on a virtualenv with the right python interpreter:
   ```bash
   $ mkvirtualenv -p python3.11 testenv
   $ pip install -e my_sources/
   $ pip install -r test/requirements.txt
   $ pre-commit run --all-files
   ```

3. Error traceback, which is the unexpected output:

   ```bash
   pycln....................................................................Failed
   - hook id: pycln
   - exit code: 1

   Looks good! ✨ 🍰 ✨
   ...
   39 files left unchanged.
   server.py:24:11 SyntaxError: invalid syntax 'except* Exception as excgroups:' ⛔
   ```

**Expected behavior**:

The exception group syntax should not result in a syntax error.

**Environment:**

- Python Version: Python 3.11
- Pycln Version: v2.4.0 (also on current [master](https://github.com/hadialqattan/pycln/commit/d0aeb62860b889f0f7b48aa9c7685d3348b5521d))
- OS Type: Linux
